### ISSUE TITLE
Font Ligatures

### ISSUE THREAD

**Issue by StephanieSunshine** [lucc/nvimpager#100]
Is there any chance nvimpager can support font ligatures like Neovim does? On Macos, I have my Neovim displaying them correctly, but nvimpager seems to ignore it.

**Comment by lucc** [comment]
Shouldn't font ligatures be the job of the terminal? What setting in neovim are you using to enable font ligatures? Can you copy it to nvimpager's init file?

**Comment by StephanieSunshine** [comment]
You are correct, there was an extra option I had enabled in Neovim to enable comments turning italic that I had misunderstood as font ligatures, that wasn't showing up in other places. Thank you.
