### ISSUE TITLE
How to move the cursor up and down?

### ISSUE THREAD

**Issue by lefthairynut** [lucc/nvimpager#105]
Hi! Now that j and k navigate the entire buffer, how can I move the cursor up and down normally like in vim? It's difficult to select text in visual mode when I have to scroll through the entire buffer to get to the desired line.

**Comment by lucc** [comment]
There is no binding for that but you can create your own bindings in your init file. You can also deactivate the default bindings with `nvimpager.maps = false`.

You could also switch to visual mode as j and k are not mapped there.

**Comment by lefthairynut** [comment]
I just put it here for reference, I ended up setting key bindings for up and down in the init file.
```
nnoremap <S-j> j
nnoremap <S-k> k

```
