### ISSUE TITLE
AnsiEsc Instructions

### ISSUE THREAD

**Issue by lovesegfault** [lucc/nvimpager#12]
I have AnsiEsc as a plugin in Neovim, but I have to manually activate it (`:AnsiEsc`) whenever I use nvimpager.

How can I automatically enable AnsiEsc whenever I open something with nvimpager?

**Comment by lucc** [comment]
Nvimpager should not share the plugins with neovim. I modify the runtimepath during startup to not load all those plugins a user might have and only need for editing.

What does `:messages` and `:scriptnames` say after you started the pager and after you executed `:AnsiEsc`? Did you install a copy of ansiEsc with the makefile? 

The ansi escaping should be triggered automatically **iff** you open a file with ansi escape sequences.  So the next question would be what file you use. Can you create a minimal one where the problem shows up?

**Comment by lovesegfault** [comment]
Okay, I'll unpack your questions/statements so it's easier for me to address them.

> Nvimpager should not share the plugins with neovim.

This has not been my experience. I have the same plugins on nvimpager as I do on nvim

> What does :messages and :scriptnames say after you started the pager and after you executed :AnsiEsc?

`:messages` does nothing.
`:scriptnames` returns a large list, which I have placed in [this gist](https://gist.github.com/0a830b07f6101d4f927e53a02da21f55).

> The ansi escaping should be triggered automatically...

Doesn't happen here :(

---

As an addendum, I'm on Gentoo, and I have nvimpager through the `nvimpager` USE flag of the `neovim` package. Which... Ah.

https://gitweb.gentoo.org/repo/gentoo.git/tree/app-editors/neovim/neovim-0.3.4-r1.ebuild#n86

This explains everything.

**Comment by lucc** [comment]
Oh well we have been there #7 :( Maybe @xi- has since managed to push an ebuild for *this* nvimpager upstream?

**Comment by lovesegfault** [comment]
I don't think so, but I'd be happy to attempt to write an ebuild for it myself. I'll open a separate issue for that :)

**Comment by ix-** [comment]
Sorry to dissapoint, I just use vimpager instead, since I did not get around fixing it.
I'd love to see a working nvimpager in gentoo though.
Best regards,
ix

On 17 May 2019 09:10:49 CEST, Lucas Hoffmann <notifications@github.com> wrote:
>Oh well we have been there #7 :( Maybe @ix- has since managed to push
>an ebuild for *this* nvimpager upstream?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/lucc/nvimpager/issues/12#issuecomment-493347175

-- 
ix
