### ISSUE TITLE
FAQ: What's the difference between this nvimpager and the one that ships with neovim?

### ISSUE THREAD

**Issue by bearcatsandor** [lucc/nvimpager#15]
Would you place a note in the readme detailing what is different about this nvimpager ( /usr/local/bin/nvimpager ) vs the one that ships with neovim ( /usr/bin/nvim )?

**Comment by lucc** [comment]
(Neo)vim ships with the less.sh and less.vim scripts which gave birth to the idea to use (neo)vim as a pager. Vimpager was an improved version of that. After some time working on vimpager I decided to make nvimpager. 

(n)vimpager has more features than the original less.sh, and is actively developed.  Thatshould be the main difference.

I will see if I find a nice place to put a note in the readme.

**Comment by bearcatsandor** [comment]
Thank you. It would be great if neovim switched to yours.

**Comment by lucc** [comment]
You can always open a PR but what is the problem with this being developed separately?

**Comment by bearcatsandor** [comment]
Nothing save for the user being given the best tool for the job, and packaging convenience.
