### ISSUE TITLE
Git colors aren't properly parsed

### ISSUE THREAD

**Issue by 3v1n0** [lucc/nvimpager#19]
Git colors work when using the default syntax highlighter

However when using it as a pager (i.e. using `GIT_PAGER="nvimpager -p" git graph`) the result isn't correct.

this pager:
![less](https://user-images.githubusercontent.com/345675/67529173-ae979e00-f6bb-11e9-8a99-347271eb43af.png)

less:
![nvimpager](https://user-images.githubusercontent.com/345675/67529205-bce5ba00-f6bb-11e9-8a33-a997632fc606.png)

**Comment by lucc** [comment]
Nvimpager uses neovim's syntax highlighting and apparently that only handles log and diff. You will have to fix this upstream.

**Comment by lucc** [comment]
FYI there was #68 which added an option `nvimpager.git_colors` that might do what you want.
