### ISSUE TITLE
Support for colors (eg with git)?

### ISSUE THREAD

**Issue by pLesur** [lucc/nvimpager#2]
Hi, when something such as:

```bash
export PAGER=less; git log --graph
```

we get something with nice colors (ie with my setup I get yellow commit hashes and red lines for the main branch line).

Doing so with nvimpager won't output any color. I do get colored man pages however so I don't know. Is that maybe a terminal colorscheme configuration?

**Comment by lucc** [comment]
Just now I also remembered the option `--color=always` for `git log`. You can try to run `git log --color | nvimpager` and nvimpager should highlight the terminal codes git gives you. This forces git log to display the terminal color escapes even though output is to a pipe and it stops nvimpager from detecting git as its parent process (the pager is not started by git so git isn't the parent process).

**Comment by plurry** [comment]
Is there any way to force `nvimpager` to draw the ANSI color codes when run by `git` if there isn't a Neovim syntax file for the output?

**Comment by lucc** [comment]
You can stop git from loading the pager itself so nvimpager will not detect a git parent process: `git log --graph --color | nvimpager`
