### ISSUE TITLE
Output is garbled when using with ri (ruby info)

### ISSUE THREAD

**Issue by jhessin** [lucc/nvimpager#24]
When I run.
```bash
ri Array
```
I get the following

```
= AArrrraayy  <<  OObbjjeecctt

------------------------------------------------------------------------
= IInncclluuddeess::
Enumerable (from ruby site)
...

```

However I do not get this when running `ri String` which produces output in cat mode.

I tried using vimpager and I don't have this problem (though my python plugins don't work with it).

**Comment by lucc** [comment]
@jhessin sorry for the long wait. Can you check the fix/24 branch (1ada83b89c06126a40e3214aeec35c957d2a6ec1)?
