### ISSUE TITLE
nvimpager use nowrapscan by default

### ISSUE THREAD

**Issue by acgtyrant** [lucc/nvimpager#5]
I noticed that it will compains `E384: search hit TOP without match for: \<ZSH\>` when I hit the start. I execute `set wrapscan?` in nvimpager, it outputs `nowrapscan` while NeoVim's help says it will set wrapscan on by default acutally.

Of course, I use the config from the NeoVim for nvimpager, the former does not set `nowrapscan`.

**Comment by lucc** [comment]
What is this bug report about? What do you want need?

If you just want to tell me how it is, I know: https://github.com/lucc/nvimpager/blob/develop/autoload/pager.vim#L106

**Comment by acgtyrant** [comment]
Why do nvimpager set `nowrapscan` by default while the NeoVim set `wrapscan` by default?

**Comment by lucc** [comment]
That is a good question. I made this decision about 2 years ago when nvimpager was not even public.  I removed it now, please try current develop.

**Comment by lucc** [comment]
Or try v0.5 :)
