### ISSUE TITLE
Manpage produced by scdoc is blank

### ISSUE THREAD

**Issue by cvoges12** [lucc/nvimpager#51]
I saw that when running make, a `nvimpager.1` was created. Without knowing much about `scdoc`, I'd assume there isn't documentation yet or scdoc is failing to find it in the source repository. 

If this is the case of being no docs, we (including myself as I remember the manpage language quite well) can choose to write the manpage by hand removing scdoc as a dependency, *or* we could try to write your `scdoc` thing.

If this is the case of `scdoc` not finding the code for the document to be created, well, now you know to fix it I guess haha.

**Comment by lucc** [comment]
Can you tell me which commit you checked out and what the makefile says?  I noticed that if scdoc is not installed the makefile generates an empty nvimpager.1 file.

**Comment by cvoges12** [comment]
Commit dce5017c14fc07d0ba775b8751d0e3de8939bf8d

And yes, `scdoc` is installed.

**Comment by cvoges12** [comment]
Same result with commit 49315df9df29a37376af1cb3e00b1708caf4cf7c

**Comment by lucc** [comment]
Can you post the complete output of `make clean && make nvimpager.1` and also tell me the version of scdoc you have or which shell you use?

**Comment by docwhat** [comment]
On macOS with `zsh` and with macOS's built in BSD-flavored `sed`:

```sh
❯ make clean && make nvimpager.1
rm -f nvimpager.configured nvimpager.1 luacov.*
sed '1cnvimpager(1) "nvimpager v0.10.2"' nvimpager.md | scdoc > nvimpager.1
sed: 1: "1cnvimpager(1) "nvimpag ...": command c expects \ followed by text
❯ cat nvimpager.1
.\" Generated by scdoc 1.11.1
.\" Complete documentation for this program is not available as a GNU info page
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.\" Begin generated content:
❯
```

In my case, I can work around it by `brew install gnu-sed` and then using this command:

```
make clean && env PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH" make nvimpager.1
```

**Comment by docwhat** [comment]
The manpage still isn't right for me.  The ["following fields" list](https://github.com/lucc/nvimpager/blame/develop/nvimpager.md#L82-L89) is missing.  I can file another bug for that or continue here since I suspect it is related.

**Comment by lucc** [comment]
@docwhat please try the latest develop branch, the sed command in your makefile has been fixed.

**Comment by docwhat** [comment]
More info:

```sh
❯ man nvimpager        
/usr/bin/tbl:<standard input>:106: unrecognised format `T'
/usr/bin/tbl:<standard input>:106: giving up on this table
```

The macOS `man` uses the builtin version of `/usr/bin/tbl` which is `GNU tbl (groff) version 1.19.2`.

**Comment by docwhat** [comment]
> @docwhat please try the latest develop branch, the sed command in your makefile has been fixed.

Cool, that fixed the `sed` issue.  I'll open a separate one for the table format issue.
