### ISSUE TITLE
Cannot close last window when hitting q

### ISSUE THREAD

**Issue by W4RH4WK** [lucc/nvimpager#58]
I've update nvimpager to verison `v0.10.3` and I can no longer close man pages directly by pressing `q`.

- `man printf` and then pressing `q` displays this message: `E444: Cannot close last window`.
- `nvimpager foo` and then pressing `q` works fine.

**Comment by lucc** [comment]
This was also reported in #56 (but that is not clear from the title so thanks for the report)

The quickfix mentioned there is to set `let g:no_man_maps = v:true` in `~/.config/nvimpager/init.vim`.

I have also been working on a better fix. Maybe you want to test the fix/man-mappings branch (34cc65a)? (info also for @mrdgo)

**Comment by W4RH4WK** [comment]
34cc65a works fine for me.
