### ISSUE TITLE
Colors are broken in cat mode

### ISSUE THREAD

**Issue by ivanp7** [lucc/nvimpager#59]
![image](https://user-images.githubusercontent.com/3432246/145694658-bdfad40c-1481-4dfb-b9e2-83a06137f4d6.png)

Pager mode works fine:
![image](https://user-images.githubusercontent.com/3432246/145694679-3da69ac1-d5e7-42be-9a84-44073d97ded6.png)

I use custom `st` build as the terminal under Artix Linux.
`nvimpager` is installed as `nvimpager-git` package (version 0.10.3.r3.g2c2e137-1) from AUR, `neovim` is of version 0.6.0

**Comment by lucc** [comment]
Can you share the example file so I can reproduce this?

**Comment by ivanp7** [comment]
```
diff --git a/fixes/smartbuy_extra_keys/install.sh b/fixes/smartbuy_extra_keys/install.sh
index 81c0194..a2f945e 100755
--- a/fixes/smartbuy_extra_keys/install.sh
+++ b/fixes/smartbuy_extra_keys/install.sh
@@ -1,9 +1,9 @@
 #!/bin/sh
 
+cat xmodmap >> "$XDG_CONFIG_HOME/X11/xmodmap"
+
 cd "$(dirname "$0")"
 MAP_FILE=smartbuy-keyboard.map
 { sudo dumpkeys | head -1; cat "$MAP_FILE"; } | sudo tee -a /usr/local/share/kbd/keymaps/$MAP_FILE
 sudo chmod 644 /usr/local/share/kbd/keymaps/$MAP_FILE
 
-cat xmodmap >> "$XDG_CONFIG_HOME/X11/xmodmap"
-
```

This happens with any patch/diff.

I also tried `nvimpager -c -- -u NORC`, got the same  problem with default colors.
With `nvimpager -c -- -u NONE` I get colorless output.

**Comment by lucc** [comment]
I am sorry I can not reproduce this with the given file. I tried termite and st from the NixOS repos. My neovim is also 0.6 from NixOS.

I checked out 2c2e137 and ran
```
./nvimpager -c ./issue-59-example.diff -u NORC
./nvimpager -c ./issue-59-example.diff
./nvimpager -p ./issue-59-example.diff -u NORC
./nvimpager -p ./issue-59-example.diff
```
For me the highlight does not leak.

Can you cross check with another terminal and maybe even vanilla st?

**Comment by lucc** [comment]
`./nvimpager -c ./issue-59-example.diff -u NORC > issue-59-example.diff.log` yields this file for me:
[issue-59-example.diff.log](https://github.com/lucc/nvimpager/files/7698735/issue-59-example.diff.log)

Is that the same for you?

**Comment by lucc** [comment]
We can also try to check your terminal. What happens if you `cat mini.txt` with this file?
[mini.txt](https://github.com/lucc/nvimpager/files/7698741/mini.txt)

**Comment by ivanp7** [comment]
Both vanilla `st` and `termite` work better, but still have uncolored spaces:
![image](https://user-images.githubusercontent.com/3432246/145712884-006348fd-bbb8-4597-9efc-6b8733d29e22.png)

> Is that the same for you?

Yes, `diff` reports outputs are the same.

> What happens if you `cat mini.txt` with this file?

All custom `st`, vanilla `st`, and `termite` show this:
![image](https://user-images.githubusercontent.com/3432246/145713099-8a964478-38e7-4d2c-935e-b6e031926e10.png)

**Comment by ivanp7** [comment]
I modified your mini.txt to show text in red background (I changed 31 to 41), and this is what I get in all terminals:
![image](https://user-images.githubusercontent.com/3432246/145717241-c138336b-718a-4910-aa50-708eb66a3134.png)

Linux console and fbterm work fine. It is not `nvimpager` problem nor `st` terminal problem. I don't know, what's going on.

**Comment by lucc** [comment]
I updated my mini.txt to background colours like you siad but I can not reproduce this.  I am currently on Arch Linux with several terminal emulators (st from aur) I get this:
![2021-12-13-095204_247x1056_scrot](https://user-images.githubusercontent.com/1104419/145791391-f4802d0e-cba3-468d-9cb9-036a00b89677.png)

**Comment by ivanp7** [comment]
I am sure now that this isn't nvimpager issue, because I've managed to reproduce the breakage in both `st` and `termite`. Right after start the colors are fine, but if I `cd` into other directory, start graphical application from there AND `cd` back, then colors break.
![image](https://user-images.githubusercontent.com/3432246/145897257-4fbcebdf-013c-42ad-af06-3e8667138fdc.png)
This is extremely odd, I cannot even guess what the reason may be.

**Comment by lucc** [comment]
Maybe your prompt uses strange escape sequences that are emitted when you `cd`?  Try `st -e /bin/sh` or so.

I will close this now, but you can still post updates, maybe I have an idea that can help :crossed_fingers: 
Maybe you might have  luck asking on unix.SE.

**Comment by ivanp7** [comment]
Thanks for help. Probably you're right, this is related to the shell... Luckily, this problem happens not that often and `reset` fixes it temporarily.
