### ISSUE TITLE
Python help pages

### ISSUE THREAD

**Issue by NDagestad** [lucc/nvimpager#61]
HI,
I discovered today that the output is a bit mangled in python when using the `help()` function.
(Not really sure what format they use)
I attached a screenshot with the where nvimpager is used in the left terminal and les in the right one.
![2022-02-24-11-57-32](https://user-images.githubusercontent.com/52493911/155511786-af6024a6-9681-4682-9c43-d7f155fd46fc.png)

Feel free to ask if more information is needed, I'm on Arch and this is with python 3.10

**Comment by lucc** [comment]
Thanks for the report I can reproduce this. I think it is related to https://github.com/neovim/neovim/issues/14090#issuecomment-913837694.

Can you try the `fix-61` branch and report back?

**Comment by NDagestad** [comment]
That does indeed fix it.
I don't have colours though, but I don't care that much about it 
(I still have colours in normal man pages)

**Comment by lucc** [comment]
I noticed the lack of colours as well. Strangely if I execute `:Man!` interactively I do get colors.

Do you happen to use perl or ruby? If so can you test if the docs for these are highlighted correctly?

**Comment by lucc** [comment]
Something that nvimpager does breaks the colours when Man is executed early.  With `PAGER='nvim -c "Man!"' python -c 'import sys;help(sys)'` the colours are displayed just fine.

**Comment by lucc** [comment]
@NDagestad I found a fix for the colors. Can you try 6fbcde5.

**Comment by NDagestad** [comment]
I don't use either but that last commit get colours back in my python docs so this seems closed to me 👍
Many thanks for the help and nvimpager in general, it has made my life much better. The simple fact that I can follow my usual instinct of mashing of the escape key a few time before doing stuff like I do in vim is such a quality of life improvement !
