### ISSUE TITLE
nvimpager doesn't work inside nvim terminal emulator

### ISSUE THREAD

**Issue by name-snrl** [lucc/nvimpager#67]
When [neovim/neovim#11009](https://github.com/neovim/neovim/pull/11009) was merged neovim started defining $NVIM when you open the terminal and it is not the path to nvim executable.

I use nvimpager as a substitute for less. This means that I cannot print systemctl status or journalctl, etc. in the nvim terminal emulator.

**Comment by lucc** [comment]
What would be better names for the variable on our end?
- NVIMPAGER_NVIM
- NVIM_COMMAND
- ...?

I checked and this and XDG_CONFIG_HOME seem to be the only environment variables that we read from outside, so there are not other variables that we have to align with.

**Comment by name-snrl** [comment]
We can simply add a check like this to maintain compatibility:

```bash
if [[ ! $("$NVIM" --version) =~ vim ]]; then
    NVIM=nvim
fi
```
