### ISSUE TITLE
Escape sequences not translated

### ISSUE THREAD

**Issue by ix-** [lucc/nvimpager#7]
Not sure, if it's really nvimpager at fault here but I tested it with PAGER set to nvimpager and less:
![nvimpager_vs_less](https://user-images.githubusercontent.com/4649962/43686031-4b738542-98bf-11e8-8c0e-85acf17d693b.png)

Both show numpy's mean docstring in ipython, left with nvimpager, right with less.

The same happens to man pages, if MANPAGER is set to nvimpager :

![nvimpager_vs_less_man](https://user-images.githubusercontent.com/4649962/43686053-8fd3eb32-98bf-11e8-9232-15347a9aeb69.png)

This is using suckless' simple terminal (st), but I tested it also with xterm, same result.
It is perfecly possible that there is some issue with my setup, but since I cannot find a remedy online, I reported this here in the hope that someone has a clue what's going on.

**Comment by ix-** [comment]
If it's relevant to anyone:

- platform: funtoo linux
- ``uname -a`` : Linux HOSTNAME 4.17.11-gentoo #2 SMP Mon Jul 30 15:16:07 CEST 2018 x86_64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz GenuineIntel GNU/Linux
- st: =x11-terms/st-0.7 (http://st.suckless.org/)
- .bashrc: 
    -   export PAGER="nvimpager"
    -   export MANPAGER="nvimpager"
- neovim: =app-editors/neovim-0.3.0

**Comment by lucc** [comment]
I can not reproduce this right away. What version of nvimpager are you running?

**Comment by ix-** [comment]
I do not have anything in .config/nvimpager/init.vim.

```

nvimpager -v
NVIM v0.3.0
Build type: Release
LuaJIT 2.0.4
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -march=corei7 -O2 -pipe -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/var/tmp/portage/app-editors/neovim-0.3.0/work/neovim-0.3.0_build/config -I/var/tmp/portage/app-editors/neovim-0.3.0/work/neovim-0.3.0/src -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.3.0/work/neovim-0.3.0_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.3.0/work/neovim-0.3.0_build/include
Compiled by root@project2501

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by lucc** [comment]
This looks like you are running a version before 0.1 as the version option is not handled by nvimpager but by nvim itself. Please update to a newer version.

**Comment by ix-** [comment]
Ok, the nvimpager comes bundled by USE flag  with neovim, I'll have to make a package myself. Thanks for your help.

On 6 August 2018 17:37:29 CEST, Lucas Hoffmann <notifications@github.com> wrote:
>This looks like you are running a version before 0.1 as the version
>option is not handled by nvimpager but by nvim itself. Please update to
>a newer version.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lucc/nvimpager/issues/7#issuecomment-410751194

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lucc** [comment]
Where can I see the sources (the ebuild file or however that is called in gentoo/funtoo) that you used?

**Comment by ix-** [comment]
The ebuild of neovim-0.3.0 can be found here:

https://github.com/funtoo/editors-kit/blob/master/app-editors/neovim/neovim-0.3.0.ebuild

It pulls the neovim release from their github archive.

src_install() installs a nvimpager symlink, which seems to be part of neovim.
Your code is actually not pulled, iiuc. So unless your project is not downstreamed to neovim, I might have been misled by the name and barked at the wrong tree. If that's the case, I'm very sorry for wasting your time.

On 6 August 2018 19:11:58 CEST, Lucas Hoffmann <notifications@github.com> wrote:
>Where can I see the sources (the ebuild file or however that is called
>in gentoo/funtoo) that you used? 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lucc/nvimpager/issues/7#issuecomment-410781007

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lucc** [comment]
I am sorry to say that it is not my code (but the code that inspired [the code](https://github.com/rkitover/vimpager) that inspired me). And here I was hoping I made in into some gentoo distro :laughing:

**Comment by ix-** [comment]
Yeah ok, then I'll see if I can craft an ebuild, if I'm handy enough. If I succeed I'll can send a pull request, so maybe it'll be included.
Thanks anyway for your prompt response!
Best regards,
Morris

On 6 August 2018 21:30:27 CEST, Lucas Hoffmann <notifications@github.com> wrote:
>I am sorry to say that it is not my code (but the code that inspired
>[the code](https://github.com/rkitover/vimpager) that inspired me). And
>here I was hoping I made in into some gentoo distro :laughing: 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lucc/nvimpager/issues/7#issuecomment-410826110

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
