### ISSUE TITLE
Disable mouse clicks

### ISSUE THREAD

**Issue by mike-lloyd03** [lucc/nvimpager#71]
I'm taking nvimpager for a test drive and I like it so far. One thing I can't live with though is that it intercepts mouse clicks and drags. I'm always in tmux and I use mouse selection for copy/pasting. But in nvimpager, selecting text selects it directly and tmux doesn't seem to be aware of the selection. Also, double clicking a word should highlight and copy it with the tmux register, but it instead opens the man page for the word selected. How can I disable this?

I'd like to disable all mouse features except scroll wheel if possible.

Thanks!

**Comment by lucc** [comment]
You can check the nvim help with `:h 'mouse'` and see what value you can put in your init.vim file. By default nvimpager uses `set mouse=a`.

**Comment by mike-lloyd03** [comment]
I looked around in there but there's not an option for my specific use case. But this is more of a general nvim question anyway so I'll close this issue.
