### ISSUE TITLE
glow previews don't work with nvimpager

### ISSUE THREAD

**Issue by Luis-Licea** [lucc/nvimpager#76]
Calling `glow -p README.md` returns an error when `PAGER=nvimpager`. This is because `glow -p` uses the `$PAGER` environment variable. A workaround is to set the `PAGER` environment variable to `less -r` or `most` and `MANPAGER` to `nvimpager` so that `nvimpager` does not get called in the first place.

I opened an issue here and in the `glow` repo so that the problem is documented.

All markdown files over a certain length give this error. I attached an example.
[test.md](https://github.com/lucc/nvimpager/files/9946940/test.md)

**Comment by lucc** [comment]
Can you please describe the error in more detail. You just state that there is *some* error.  Normally you would describe what you expect to happen and what actually happend in a bug report.  Please provide all relevant info so that others can reproduce the error.
