### ISSUE TITLE
nvimpager fails when executed without options in a script

### ISSUE THREAD

**Issue by ivanp7** [lucc/nvimpager#85]
I have a script:

```
#!/bin/sh
exec nvimpager -p -- "$@"
```

It works, but when I remove `-p`, nvimpager fails:

```
Error detected while processing VimEnter Autocommands for "*":
E5108: Error executing lua /usr/share/nvimpager/runtime/lua/nvimpager.lua:147: attempt to call upvalue 'color2escape' (a nil value)
stack traceback:
    /usr/share/nvimpager/runtime/lua/nvimpager.lua:147: in function 'group2ansi'
    /usr/share/nvimpager/runtime/lua/nvimpager.lua:161: in function 'init_cat_mode'
    /usr/share/nvimpager/runtime/lua/nvimpager.lua:297: in function 'cat_mode'
    [string ":lua"]:1: in main chunk
```

and prints nothing.

**Comment by lucc** [comment]
I can not reproduce this. Can you tell me which version of nvimpager you have and how you are calling your script?

**Comment by ivanp7** [comment]
My nvimpager is `nvimpager v0.10.4-18-g7a0b5dd`, installed from AUR as nvimpager-git

I can run `ls | nvimpager` and get the error.

**Comment by lucc** [comment]
Your version is from 2022-01,can you please update to the newest version.

**Comment by ivanp7** [comment]
My bad, I have assumed that the package was the latest version. I will try the new version and post the result.

**Comment by ivanp7** [comment]
Yep, the problem went away. Thanks for helping out.
