### ISSUE TITLE
When wrapping with Nix to set arguments, always uses `cat` mode

### ISSUE THREAD

**Issue by spikespaz** [lucc/nvimpager#89]
I have the following Nix derivation, which will replace the `nvimpager` command with a wrapper script:
```nix
nvimpager' = pkgs.nvimpager.overrideAttrs (self: super: {
  nativeBuildInputs = super.nativeBuildInputs or [ ] ++ [ pkgs.makeWrapper ];
  postInstall = super.postInstall or "" + ''
    wrapProgram $out/bin/nvimpager \
      --add-flags '-p -c "lua nvimpager.maps = false; lua nvimpager.git_colors = true"'
  '';
});
```

This is the content of the script:
```sh
#! /nix/store/ir0j7zqlw9dc49grmwplppc7gh0s40yf-bash-5.2-p15/bin/bash -e
exec -a "$0" "/nix/store/gms73z8zvfps98rdkcf2r5xs1pbay0lc-nvimpager-0.12.0/bin/.nvimpager-wrapped"  -p -c "lua nvimpager.maps = false; lua nvimpager.git_colors = true" "$@"
```

When I use the pager for anything from STDIN, it always just prints out the content (syntax highlighted) to my terminal.

**Comment by lucc** [comment]
In your script you have the options `-p -c` which are both parsed by nvimpager. Nvim options can only be given after  `--` or after a file argument.

**Comment by spikespaz** [comment]
If they're parsed by nvimpager why do they need to be after `--`?

**Comment by spikespaz** [comment]
Oh I see, I need to end the arguments parsed by `nvimpager` with `--`.

**Comment by lucc** [comment]
You need `nvimpager -p -- -c "lua nvimpager.maps ..."` because you want to use the `-c` option of nvim but are actually using the -c option of nvimpager (with a file nameof "lua nvimpager.maps = ..." which probably does not exist).

**Comment by spikespaz** [comment]
Alright, I've got that. Now what is the correct way to set multiple attributes with Lua?
```
Error detected while processing command line:
E5107: Error loading lua [string ":lua"]:1: '=' expected near 'nvimpager'
```

**Comment by lucc** [comment]
You are mixing vim script and lua. You need `lua nvimpager.maps = false; nvimpager.git_colors = true`
