### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by lifranc** [lucc/nvimpager#9]
```
curl http://www.drchip.org/astronaut/vim/vbafiles/AnsiEsc.vba.gz | \
	  gunzip > $@
```
No SSL even...

**Comment by lucc** [comment]
It's very nice and clear that we are all important people who don't have time to explain, but what are you concerns apart from the missing SSL? (Which could have been solved with a small PR very easily ;)

**Comment by lifranc** [comment]
A good test to find out if a makefile is sane is to build it with nix. I would suggest reading about functional builds. Good luck
