### ISSUE TITLE
Git diff uses "Identifier" highlight group for "Adding" lines

### ISSUE THREAD

**Issue by igorgue** [lucc/nvimpager#93]
I'm a theme developer, when I try to run `git diff` the colors nvimpager picks up for the "Added lines" highlight is "Identifier" I have that color similar to "Normal" (fg) and unfortunately I cannot see the "+" with that color.

Is there a way to figure out the highlight group to change in my theme?

**Comment by lucc** [comment]
I think that is `nvim/runtime/syntax/diff.vim` line 382.

I did
1. `git diff HEAD~20`
1. `:set ft?`
1. `:scriptnames`
1. `:tabedit .....nvim/runtime/syntax/git.vim`
1. `/Identifier`  brings me to line 103: `hi def link gitHash              Identifier` that does not look right
1. `/include` brings me to line 13: `syn include @gitDiff syntax/diff.vim`
1. `:scriptnames`
1. `:tabedit .....nvim/runtime/syntax/diff.vim`
1. `/Identifier`
