### ISSUE TITLE
Is it possible to use pure lua to refactor this project?

### ISSUE THREAD

**Issue by Freed-Wu** [lucc/nvimpager#94]
neovim have a lua interpreter. If this project can use it to reduce dependency of bash, it will be better?

`nvimpager`:

```lua
#!/usr/bin/env -S nvim -u NONE -l
-- ...
```

**Comment by lucc** [comment]
It is possible to do that but you have to reimplement the command line parsing and some other details that bash offers.

In my opinion that is more work than it is worth.  I assume that most systems already  have bash installed for some other reason (so I do not consider it a "big" dependency; on my NixOS system for example the full dependency tree of bash is 34MB and the full dependency tree of neovim is 91MB and also includes bash)

Is there any problem with bash as a dependency?

**Comment by Freed-Wu** [comment]
Not all OSs preinstalled bash. Some BSDs installed other shells like ksh as their shell, Some OSs like win even don't have bash. However, in any situation, neovim's lua is accessible.

> reimplement the command line parsing

It shouldn't be very complex, just parse `vim.v.argv` is OK.

> some other details that bash offers

Do you mean `[ -t tty ]`?

**Comment by lucc** [comment]
I meant redirection and environment exports which are more involved with vim functions than with bash.

If some system does not *preinstall* bash that is not a problem in my opinion. I suspect most systems do not preinstall neovim either. If a system does not *provide* bash then you have a point: currently nvimpager is not usable on that system.

Although you Windows is not a priority for me and you can certainly install bash on windows here are some other things that you have to check if and how they can be achived in lua or on windows:
- the nvimpager script uses `tput` to count the lines in the terminal
- the script uses `exec` to start neovim at the end
- the script exports environment variables to communicate some values to the nvimpager lua code without shell quoting issues
- the lua code uses nvim_get_proc to detect certain parent processes

I am not motivated to port the bash script to lua but you can try.

**Comment by Freed-Wu** [comment]
A simplest lua script is like

```lua
#!/usr/bin/env -S nvim --headless -l
vim.cmd.edit(arg[1])
require("nvimpager.cat").cat_mode()
```

Put nvimpager in `$LUA_PATH_5_1`. to let it can be find.

`nvim.nvim_command('quitall!')` is unnecessary due to lua script will exit on EOF.

`vim.cmd.edit()` is very slow. In my test, it cost > 100 times than [bat](https://github.com/sharkdp/bat)

Own neovim's syntax highlight ecosystem and high speed is a challenge.

PS: a tool [syncat](https://github.com/foxfriends/syncat) can get tree-sitter ecosystem and high speed.
