### ISSUE TITLE
display number like bat

### ISSUE THREAD

**Issue by Freed-Wu** [lucc/nvimpager#95]
I want the effect of bat, however

![Screenshot from 2024-02-20 11-23-52](https://github.com/lucc/nvimpager/assets/32936898/1e6cae3e-4cf1-4448-8bbc-efcf29adc914)

Can nvimpager display number like bat?

**Comment by lucc** [comment]
Cat mode can not, so you have to use `nl` or `cat -n`.  In pager mode you can `set number`.
